"""
DAG Runner — executes structured task graphs generated by the Planning Engine.

Features:
  - Graph-based step execution (nodes + directed edges)
  - Parallel execution of independent steps (same depth level)
  - Retry strategy (configurable, default 2 retries)
  - Fallback edges on failure
  - EventBus publishing after each step
  - Returns a full DAGResult for feedback loop integration
"""
from __future__ import annotations

import logging
import time
import uuid
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable

logger = logging.getLogger(__name__)


@dataclass
class DAGNode:
    """A single node (step) in the execution graph."""
    id: str
    type: str                                  # e.g. open_app, run_command, tell_user
    params: Dict[str, Any] = field(default_factory=dict)
    requires_confirmation: bool = False
    on_success: Optional[str] = None           # ID of next node on success
    on_failure: Optional[str] = None           # ID of next node on failure
    max_retries: int = 2
    description: str = ""


@dataclass
class ExecutionDAG:
    """Validated task graph ready for execution."""
    start_node: str
    nodes: Dict[str, DAGNode]                  # node_id → DAGNode
    dag_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    description: str = ""

    @classmethod
    def from_dict(cls, raw: Dict[str, Any]) -> "ExecutionDAG":
        """Convert a raw LLM-generated dict into a typed ExecutionDAG."""
        start = raw.get("start_node", "")
        raw_nodes = raw.get("nodes", {})
        nodes: Dict[str, DAGNode] = {}

        for nid, nd in raw_nodes.items():
            nodes[nid] = DAGNode(
                id=nid,
                type=nd.get("type", "tell_user"),
                params=nd.get("params", {}),
                requires_confirmation=nd.get("requires_confirmation", False),
                on_success=nd.get("on_success"),
                on_failure=nd.get("on_failure"),
                max_retries=nd.get("max_retries", 2),
                description=nd.get("description", ""),
            )
        return cls(start_node=start, nodes=nodes)

    def is_valid(self) -> bool:
        return bool(self.start_node and self.start_node in self.nodes)


@dataclass
class StepResult:
    node_id: str
    success: bool
    message: str
    retries_used: int = 0
    elapsed_ms: float = 0.0


@dataclass
class DAGResult:
    dag_id: str
    success: bool
    steps_executed: List[StepResult] = field(default_factory=list)
    failed_steps: List[str] = field(default_factory=list)
    final_message: str = ""
    total_elapsed_ms: float = 0.0


class DAGRunner:
    """
    Traverses and executes an ExecutionDAG using the provided Executor.
    Publishes task.step_completed / task.step_failed events to the EventBus.
    """

    def __init__(self, executor: Any, max_parallel: int = 3):
        """
        :param executor: jarvis.execution.executor.Executor instance
        :param max_parallel: Maximum concurrent parallel workers
        """
        self._executor = executor
        self._max_parallel = max_parallel

    def run(
        self,
        dag: ExecutionDAG,
        confirmation_callback: Optional[Callable[[DAGNode], bool]] = None,
    ) -> DAGResult:
        """
        Execute the full DAG starting from start_node.
        Returns a DAGResult summarizing all outcomes.
        """
        from jarvis.core.event_bus import bus, SystemEvent, EventPriority
        from jarvis.core.world_state import world

        if not dag.is_valid():
            return DAGResult(dag_id=dag.dag_id, success=False, final_message="Invalid DAG: missing start node.")

        logger.info(f"[DAGRunner] Starting DAG '{dag.dag_id}' from node '{dag.start_node}'.")
        task_id = f"dag-{dag.dag_id}"
        world.add_active_task(task_id, dag.description or f"DAG {dag.dag_id}")

        t_start = time.time()
        result = DAGResult(dag_id=dag.dag_id, success=True)

        current_node_id: Optional[str] = dag.start_node
        visited: set = set()

        try:
            while current_node_id:
                if current_node_id in visited:
                    logger.warning(f"[DAGRunner] Cycle detected at node '{current_node_id}'. Stopping.")
                    break
                visited.add(current_node_id)

                node = dag.nodes.get(current_node_id)
                if not node:
                    logger.error(f"[DAGRunner] Node '{current_node_id}' not found in DAG.")
                    break

                # ── Confirmation Gate ──────────────────────────────────────
                if node.requires_confirmation and confirmation_callback:
                    approved = confirmation_callback(node)
                    if not approved:
                        logger.info(f"[DAGRunner] Node '{node.id}' skipped (user denied confirmation).")
                        result.steps_executed.append(StepResult(
                            node_id=node.id, success=False,
                            message="User denied confirmation.", retries_used=0
                        ))
                        current_node_id = node.on_failure
                        continue

                # ── Execute Node ───────────────────────────────────────────
                step_result = self._execute_node(node)
                result.steps_executed.append(step_result)

                # ── Publish Event ──────────────────────────────────────────
                if step_result.success:
                    world.add_history(f"✓ {node.type}: {step_result.message[:80]}")
                    bus.publish(SystemEvent(
                        name="task.step_completed",
                        data={
                            "dag_id": dag.dag_id,
                            "node_id": node.id,
                            "type": node.type,
                            "message": step_result.message,
                            "elapsed_ms": step_result.elapsed_ms,
                        },
                        priority=EventPriority.NORMAL,
                    ))
                    current_node_id = node.on_success
                else:
                    result.failed_steps.append(node.id)
                    world.add_history(f"✗ {node.type}: {step_result.message[:80]}")
                    bus.publish(SystemEvent(
                        name="task.step_failed",
                        data={
                            "dag_id": dag.dag_id,
                            "node_id": node.id,
                            "type": node.type,
                            "error": step_result.message,
                            "retries": step_result.retries_used,
                        },
                        priority=EventPriority.HIGH,
                    ))
                    if node.on_failure:
                        current_node_id = node.on_failure
                    else:
                        result.success = False
                        break

        finally:
            result.total_elapsed_ms = (time.time() - t_start) * 1000
            world.complete_active_task(task_id)

        # Determine final message
        if result.failed_steps:
            result.success = False
            result.final_message = f"Completed with {len(result.failed_steps)} failed step(s): {', '.join(result.failed_steps)}"
        else:
            result.final_message = f"All {len(result.steps_executed)} step(s) completed successfully."

        logger.info(f"[DAGRunner] DAG '{dag.dag_id}' finished: {result.final_message} ({result.total_elapsed_ms:.0f}ms)")
        return result

    def _execute_node(self, node: DAGNode) -> StepResult:
        """Execute a single node with retry logic."""
        t_start = time.time()
        retries = 0
        last_result: Dict[str, Any] = {}

        # Build a step-compatible object for the executor
        step_data = {"type": node.type, **node.params}

        while retries <= node.max_retries:
            try:
                last_result = self._executor.execute_step(step_data)
                if last_result.get("success"):
                    elapsed = (time.time() - t_start) * 1000
                    return StepResult(
                        node_id=node.id,
                        success=True,
                        message=last_result.get("message", ""),
                        retries_used=retries,
                        elapsed_ms=elapsed,
                    )
                else:
                    retries += 1
                    if retries <= node.max_retries:
                        logger.warning(f"[DAGRunner] Node '{node.id}' failed (attempt {retries}). Retrying...")
                        time.sleep(0.5 * retries)
            except Exception as e:
                retries += 1
                last_result = {"success": False, "message": str(e)}
                if retries <= node.max_retries:
                    logger.warning(f"[DAGRunner] Node '{node.id}' exception (attempt {retries}): {e}. Retrying...")
                    time.sleep(0.5 * retries)

        elapsed = (time.time() - t_start) * 1000
        return StepResult(
            node_id=node.id,
            success=False,
            message=last_result.get("message", "All retries exhausted."),
            retries_used=retries - 1,
            elapsed_ms=elapsed,
        )

    def run_parallel_group(
        self,
        nodes: List[DAGNode],
        dag_id: str,
    ) -> List[StepResult]:
        """
        Execute a list of independent nodes in parallel.
        Used for DAG levels where multiple nodes have no dependencies on each other.
        """
        from jarvis.core.event_bus import bus, SystemEvent, EventPriority

        results: List[StepResult] = []
        with ThreadPoolExecutor(max_workers=min(len(nodes), self._max_parallel)) as pool:
            futures = {pool.submit(self._execute_node, node): node for node in nodes}
            for future in as_completed(futures):
                node = futures[future]
                try:
                    step_result = future.result()
                    results.append(step_result)
                    event_name = "task.step_completed" if step_result.success else "task.step_failed"
                    bus.publish(SystemEvent(
                        name=event_name,
                        data={"dag_id": dag_id, "node_id": node.id, "parallel": True},
                        priority=EventPriority.NORMAL,
                    ))
                except Exception as e:
                    results.append(StepResult(node_id=node.id, success=False, message=str(e)))

        return results
