"""
SkillSynthesizer — Dynamic Skill Synthesis for JARVIS (Phase 10).

When JARVIS encounters a SENSE_GAP intent (a request it cannot fulfil with
any registered skill), this module:
  1. Asks the LLM to write a Python skill file.
  2. Validates the generated code for safety.
  3. Writes it to jarvis/skills/synthesized/<slug>.py.
  4. Loads it into the running SkillManager.
  5. Records it in memory so it persists across restarts.

Safety model:
  - Banned imports / builtins are blocked at the text level.
  - The generated code is exec()'d in an isolated namespace — it NEVER has
    access to the live system namespace.
  - A DryRun flag prevents file writes during testing.
"""

from __future__ import annotations

import importlib.util
import inspect
import logging
import re
import sys
import tempfile
import textwrap
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from jarvis.skills.base import SkillManager
    from jarvis.memory.manager import MemoryManager

logger = logging.getLogger(__name__)

# ── Safety blocklist ──────────────────────────────────────────────────────────

_BANNED_PATTERNS: List[str] = [
    r"\bos\.system\b",
    r"\bsubprocess\.call\b",
    r"\bsubprocess\.Popen\b",
    r"__import__\(",
    r"\beval\(",
    r"\bexec\(",
    r"\bcompile\(",
    r"\bopen\s*\(.*['\"]w['\"]",          # write-mode file opens
    r"shutil\.(rmtree|move|copy)",
    r"\brm\s+-rf\b",
    r"socket\.connect",
]

_BANNED_REGEX = [re.compile(p) for p in _BANNED_PATTERNS]


def _is_safe(code: str) -> tuple[bool, str]:
    """Return (True, '') if code passes safety checks, else (False, reason)."""
    for pattern in _BANNED_REGEX:
        m = pattern.search(code)
        if m:
            return False, f"Blocked pattern: {m.group()}"
    return True, ""


# ── Skill template ────────────────────────────────────────────────────────────

_SKILL_TEMPLATE = '''"""
Auto-synthesized skill: {name}
Generated by JARVIS SkillSynthesizer in response to: {request}
"""

from __future__ import annotations
from jarvis.skills.base import Skill, SkillResult
from jarvis.nlp.schemas import Intent, IntentType


class {class_name}(Skill):
    name = "{name}"
    intent_types = [IntentType.COMMAND, IntentType.QUESTION]
    triggers = {triggers}

    def can_handle(self, intent: Intent) -> bool:
        low = intent.raw_text.lower()
        return any(t in low for t in self.triggers)

    def execute(self, intent: Intent, context=None) -> SkillResult:
{execute_body}
'''


# ── Main class ────────────────────────────────────────────────────────────────

class SkillSynthesizer:
    """
    Writes, validates, persists, and hot-loads Python skills at runtime.
    """

    def __init__(
        self,
        llm_client: Any,
        skill_manager: "SkillManager",
        memory_manager: "MemoryManager",
        skills_dir: Optional[Path] = None,
        dry_run: bool = False,
    ) -> None:
        self.llm = llm_client
        self.skills = skill_manager
        self.memory = memory_manager
        self.dry_run = dry_run

        if skills_dir is None:
            # Place synthesized skills next to the built-in skills
            skills_dir = Path(__file__).resolve().parent.parent / "skills" / "synthesized"
        self.skills_dir = Path(skills_dir)
        self.skills_dir.mkdir(parents=True, exist_ok=True)

        # Ensure the package is importable
        init = self.skills_dir / "__init__.py"
        if not init.exists():
            init.write_text("# auto-generated\n")

    # ── Public API ─────────────────────────────────────────────────────────────

    def synthesize(self, request: str, gap_description: str = "") -> Dict[str, Any]:
        """
        Attempt to synthesize a new skill for *request*.

        Returns a dict with keys:
          success (bool), skill_name (str), message (str), code (str)
        """
        logger.info(f"[SkillSynth] Attempting synthesis for: {request!r}")

        # 1. Generate code via LLM
        code = self._generate_code(request, gap_description)
        if not code:
            return {"success": False, "skill_name": "", "message": "LLM returned no code.", "code": ""}

        # 2. Safety check
        ok, reason = _is_safe(code)
        if not ok:
            logger.warning(f"[SkillSynth] Blocked unsafe code: {reason}")
            return {"success": False, "skill_name": "", "message": f"Safety block: {reason}", "code": code}

        # 3. Extract class name + skill name from generated code
        class_name, skill_name = self._extract_names(code, request)

        # 4. Write to disk
        slug = re.sub(r"[^a-z0-9_]", "_", skill_name.lower())[:40]
        skill_path = self.skills_dir / f"{slug}.py"

        if not self.dry_run:
            skill_path.write_text(code, encoding="utf-8")
            logger.info(f"[SkillSynth] Wrote skill to {skill_path}")

        # 5. Load and register
        loaded = self._load_skill(skill_path, class_name)
        if loaded:
            self.skills.register(loaded)
            logger.info(f"[SkillSynth] Registered skill: {skill_name}")

        # 6. Persist in memory
        self.memory.add_skill_pattern(
            pattern_signature=request[:100],
            example_commands=[request],
            proposed_skill_name=skill_name,
            status="synthesized" if loaded else "draft",
        )

        if loaded:
            return {
                "success": True,
                "skill_name": skill_name,
                "message": f"Synthesized and loaded skill '{skill_name}'.",
                "code": code,
            }
        return {
            "success": False,
            "skill_name": skill_name,
            "message": "Code written but could not be loaded dynamically.",
            "code": code,
        }

    def load_persisted_skills(self) -> int:
        """Load all previously synthesized skills from disk on startup."""
        count = 0
        for py_file in self.skills_dir.glob("*.py"):
            if py_file.name.startswith("__"):
                continue
            class_name = self._guess_class_name_from_file(py_file)
            skill = self._load_skill(py_file, class_name)
            if skill:
                self.skills.register(skill)
                count += 1
        if count:
            logger.info(f"[SkillSynth] Loaded {count} persisted synthesized skill(s).")
        return count

    # ── Private helpers ────────────────────────────────────────────────────────

    def _generate_code(self, request: str, gap: str) -> str:
        prompt = textwrap.dedent(f"""
        You are an expert Python developer extending the JARVIS assistant.

        The user asked: "{request}"
        Gap description: "{gap or 'No existing skill can handle this.'}"

        Write a complete Python skill class that handles this request.
        Rules:
        - Subclass `Skill` from `jarvis.skills.base`
        - Return a `SkillResult` from the `execute` method
        - `SkillResult.text` must be a string the user will HEAR
        - No OS shell calls, no file writes, no network (except via `requests.get`)
        - Keep it under 60 lines
        - Include only the class — no `if __name__ == "__main__"`

        Return ONLY the Python code, no markdown fences.
        """).strip()

        try:
            code = self.llm.generate(prompt)
            # Strip any accidental markdown fences
            code = re.sub(r"^```[a-z]*\n?", "", code.strip(), flags=re.MULTILINE)
            code = re.sub(r"```$", "", code.strip(), flags=re.MULTILINE)
            return code.strip()
        except Exception as exc:
            logger.error(f"[SkillSynth] LLM call failed: {exc}")
            return ""

    def _extract_names(self, code: str, request: str) -> tuple[str, str]:
        """Extract class name and skill name from generated code."""
        m = re.search(r"^class\s+(\w+)\s*\(", code, re.MULTILINE)
        class_name = m.group(1) if m else "SynthesizedSkill"

        n = re.search(r'name\s*=\s*["\']([^"\']+)["\']', code)
        skill_name = n.group(1) if n else class_name

        return class_name, skill_name

    def _load_skill(self, path: Path, class_name: str) -> Optional[Any]:
        """Dynamically import a skill from a file path."""
        if not path.exists():
            return None
        try:
            spec = importlib.util.spec_from_file_location(
                f"jarvis.skills.synthesized.{path.stem}", path
            )
            mod = importlib.util.module_from_spec(spec)
            sys.modules[spec.name] = mod
            spec.loader.exec_module(mod)

            cls = getattr(mod, class_name, None)
            if cls is None:
                # Fallback: find any Skill subclass in the module
                from jarvis.skills.base import Skill
                for attr in vars(mod).values():
                    if inspect.isclass(attr) and issubclass(attr, Skill) and attr is not Skill:
                        cls = attr
                        break

            return cls() if cls else None
        except Exception as exc:
            logger.error(f"[SkillSynth] Failed to load {path}: {exc}")
            return None

    @staticmethod
    def _guess_class_name_from_file(path: Path) -> str:
        try:
            text = path.read_text(encoding="utf-8")
            m = re.search(r"^class\s+(\w+)\s*\(", text, re.MULTILINE)
            return m.group(1) if m else "SynthesizedSkill"
        except Exception:
            return "SynthesizedSkill"
